ktor {
    application {
        modules = [ hu.tb.ApplicationKt.module ]
    }
    deployment {
        port = 8080
        shutdown.url = "/shutdown"
    }
}

build {
    isDeveloperMode = false
}
jwt {
    issuer = "http://0.0.0.0:8080/"
    audience = "user messenger app"
    realm = "message app"
}