[versions]
agp = "9.2.1"
androidTools = "32.2.1"
coreKtx = "1.18.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
kotlin = "2.3.21"
composeBom = "2026.05.00"
#ksp = "2.3.4"
koin = "4.2.1"
uiTextGoogleFonts = "1.11.1"
ktor = "3.5.0"
datastoreVersion = "1.2.1"
kotlinxSerJson = "1.11.0"
kotlinxSerJsonPlugin = "2.3.21"
nav3Core = "1.1.1"

#Project settings
minSdk = "26"
compileSdk = "37"
targetSdk = "37"

[libraries]
androidx-compose-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" } #used in build-logic/AndroidCompose.kt
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" } #used in build-logic/AndroidCompose.kt
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" } #used in build-logic/AndroidCompose.kt
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" } #used in build-logic/AndroidLibComposeConventionPlugin.kt
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-seralization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastoreVersion" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerJson" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
#ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization-json = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerJsonPlugin" }

chat-android-application = { id = "chat.android.application" }
chat-android-application-compose = { id = "chat.android.application.compose" }
chat-android-library = { id = "chat.android.library" }
chat-android-library-compose = { id = "chat.android.library.compose" }
chat-koin = { id = "chat.koin" }
chat-ktor = { id = "chat.ktor" }
chat-jvm-library = { id = "chat.jvm.library" }

[bundles]
koin = [
    "koin", "koin-compose"
]
ktor = [
    "ktor-core", "ktor-okhttp", "ktor-content-negotiation", "ktor-seralization-json"
]
datastore = [
    "datastore", "kotlinx-serialization-json"
]
nav3 = [
    "androidx-navigation3-runtime", "androidx-navigation3-ui"
]